[tool.poetry]
name = "36-hours-a-day"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.104.1"
uvicorn = {extras = ["standard"], version = "^0.24.0.post1"}
pydantic-settings = "^2.1.0"


[tool.poetry.group.dev.dependencies]
ruff = "^0.1.6"
pre-commit = "^3.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py312"
ignore = ["D"]
line-length = 120

[tool.ruff.extend-per-file-ignores]
"__init__.py" = ["F401"]
"models.py"=["F821"]

[tool.ruff.format]
quote-style = "double"
