openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/v1/dialers/:
    get:
      operationId: listDialers
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dialer'
          description: ''
      tags:
      - api
  /api/v1/dialers/{id}/:
    get:
      operationId: retrieveDialer
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0414\u0438\u043B\u0435\
          \u0440."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dialer'
          description: ''
      tags:
      - api
  /api/v1/dialer_prices/:
    get:
      operationId: listDealerPrices
      description: ''
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=4
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=2
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/DialerPrice'
          description: ''
      tags:
      - api
  /api/v1/dialer_prices/{id}/:
    get:
      operationId: retrieveDealerPrice
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0422\u043E\u0432\u0430\
          \u0440 \u0434\u0438\u043B\u0435\u0440\u0430."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DialerPrice'
          description: ''
      tags:
      - api
  /api/v1/dialer_prices/{id}/get_data_for_marking/:
    get:
      operationId: getDataForMarkingDealerPrice
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0422\u043E\u0432\u0430\
          \u0440 \u0434\u0438\u043B\u0435\u0440\u0430."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DialerPrice'
          description: ''
      tags:
      - api
  /api/v1/products/:
    get:
      operationId: listProducts
      description: ''
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=4
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=2
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
          description: ''
      tags:
      - api
  /api/v1/products/{id}/:
    get:
      operationId: retrieveProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u041F\u0440\u043E\u0434\
          \u0443\u043A\u0442."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
      tags:
      - api
  /api/v1/dialer_prices/{id}/set_link_with_product/{pr_id}/:
    post:
      operationId: setLinkWithProductDealerPrice
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0422\u043E\u0432\u0430\
          \u0440 \u0434\u0438\u043B\u0435\u0440\u0430."
        schema:
          type: string
      - name: pr_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DialerPrice'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/DialerPrice'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/DialerPrice'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DialerPrice'
          description: ''
      tags:
      - api
  /api/auth/token/login/:
    post:
      operationId: createTokenCreate
      description: Use this endpoint to obtain user authentication token.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenCreate'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenCreate'
          description: ''
      tags:
      - api
  /api/auth/token/logout/:
    post:
      operationId: createTokenDestroy
      description: Use this endpoint to logout user (remove user authentication token).
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
components:
  schemas:
    Dialer:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
      required:
      - name
    DialerPrice:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        product_key:
          type: string
          maxLength: 255
        price:
          type: string
          format: decimal
          multipleOf: 0.01
          maximum: 100000000000
          minimum: -100000000000
        product_url:
          type: string
        product_name:
          type: string
          maxLength: 255
        date:
          type: string
          format: date
        dealer:
          type: object
          properties:
            id:
              type: integer
              readOnly: true
            name:
              type: string
              maxLength: 100
          required:
          - name
          readOnly: true
        is_defined:
          type: string
          readOnly: true
        product_cust:
          type: string
          readOnly: true
      required:
      - product_key
      - price
      - product_url
      - product_name
      - date
    Product:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        article:
          type: string
          maxLength: 30
        ean_13:
          type: integer
        name:
          type: string
          maxLength: 255
        cost:
          type: string
          format: decimal
          multipleOf: 0.01
          maximum: 100000000000
          minimum: -100000000000
        min_recommended_price:
          type: string
          format: decimal
          multipleOf: 0.01
          maximum: 100000000000
          minimum: -100000000000
        recommended_price:
          type: string
          format: decimal
          multipleOf: 0.01
          maximum: 100000000000
          minimum: -100000000000
        category_id:
          type: integer
        ozon_name:
          type: string
          maxLength: 255
        name_1c:
          type: string
          maxLength: 255
        wb_name:
          type: string
          maxLength: 255
        ozon_article:
          type: string
        wb_article:
          type: string
        ym_article:
          type: string
        wb_article_td:
          type: string
      required:
      - article
      - ean_13
      - name
      - cost
      - min_recommended_price
      - recommended_price
      - category_id
      - ozon_name
      - name_1c
      - wb_name
      - ozon_article
      - wb_article
      - ym_article
      - wb_article_td
    TokenCreate:
      type: object
      properties:
        password:
          type: string
        username:
          type: string
