version: "3.9"

services:

  postgres:
    # image: postgis/postgis:15-3.4
    image: postgres:13
    env_file: .env
    # container_name: postgres_prosset_infra
    restart: always
    # environment:
    #   - POSTGRES_DB=${POSTGRES_DB}
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - POSTGRES_PORT=${POSTGRES_PORT}
    # ports:
    #   - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 3s
    # networks:
    #   - services

  backend:
    image: prosept/backend_prossept
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/ 

  nginx:
    image: nginx:1.19.3
    env_file: .env    
    depends_on:
      - backend    
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - media_volume:/usr/share/nginx/html/media/   

volumes:
  postgres_data:
  static_volume:
  media_volume:

# networks:
#   services:
#     name: prosset
