version: "3.9"

services:

  postgres:
    image: postgres:15-alpine
    env_file: .env
    ports:
      - "5432:5432"
    # container_name: postgres_prosept
    volumes:
      - data:/var/lib/postgresql/data/
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
    #   interval: 3s
    #   timeout: 3s
    #   retries: 5
    #   start_period: 3s

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file: .env
    # container_name: backend_prossept
    depends_on:
      - postgres
    volumes:
      # - static:/app/static/
      - static:/backend_static/
      - media:/app/media/

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - static:/app/result_build/build
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    # container_name: nginx_prossept
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - media:/usr/share/nginx/html/media/

  ml:
    build:
      context: ../ml
      dockerfile: Dockerfile
    restart: always
    # env_file: .env
    depends_on:
      - nginx

volumes:
  data:
  static:
  media:
