version: "3.9"

services:

  postgres:
    image: postgres:15-alpine
    container_name: postgres_prossept_infra
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - services

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    networks:
      - services

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - media_volume:/usr/share/nginx/html/media/
    networks:
      - services

  ml:
    build:
      context: ../ml
      dockerfile: Dockerfile
    restart: always
    # env_file: .env
    depends_on:
      - nginx
    networks:
      - services

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    networks:
      - services

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  services:
    name: prossept
