# Generated by Django 4.2.7 on 2023-11-28 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealerPrice',
            fields=[
                ('product_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('product_url', models.TextField()),
                ('product_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Dialer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=30)),
                ('ean_13', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=13)),
                ('min_recommended_price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('recommended_price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('category_id', models.IntegerField()),
                ('ozon_name', models.CharField(max_length=255)),
                ('name_1c', models.CharField(max_length=255)),
                ('wb_name', models.CharField(max_length=255)),
                ('ozon_article', models.TextField()),
                ('wb_article', models.TextField()),
                ('ym_article', models.TextField()),
                ('wb_article_td', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductDialerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('product_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.dealerprice')),
            ],
        ),
        migrations.AddField(
            model_name='dealerprice',
            name='dealer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialer_prices', to='product.dialer'),
        ),
    ]
