# Generated by Django 4.2.7 on 2023-12-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean_13',
            field=models.PositiveBigIntegerField(),
        ),
    ]
