# Generated by Django 4.2.7 on 2023-12-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_ean_13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdialerkey',
            name='product_key',
            field=models.CharField(max_length=255),
        ),
    ]
