# Generated by Django 4.2.7 on 2023-12-03 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productdialerkey_product_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_key', models.CharField(max_length=255)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ml', to='product.product')),
            ],
            options={
                'verbose_name': 'Связка ML',
                'verbose_name_plural': 'Связки ML',
            },
        ),
    ]
