name: Deploy

on:
  pull_request:
    branches:
      - developDRF
  push:

jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push backend to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./backend/
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest
      - name: Push frontend to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./frontend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest
      - name: Push ml to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./ml/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ml:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    # # if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "infra/docker-compose.yml, infra/nginx.conf"
          target: "infra"
          strip_components: 1
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd infra
            sudo docker compose -f docker-compose.yml pull
            sudo docker compose -f docker-compose.yml down --volumes
            sudo docker compose -f docker-compose.yml up -d
            sudo docker compose -f docker-compose.yml exec backend python manage.py migrate
            sudo docker compose -f docker-compose.yml exec backend python manage.py collectstatic --no-input
            sudo docker compose -f docker-compose.yml exec backend python manage.py loaddata database_dump.json
            sudo docker compose -f docker-compose.yml exec backend cp -r /app/backend_static/. /backend_static/static/
